### PR TITLE
correction of put_detail

### PR DESCRIPTION
**Pull request by hugolarzabal**
currently put_detail and patch_detail do not allow to edit if the user is different.
This PR, correct this issue.

### CODE REVIEW

**Review by ggsdc — CHANGES_REQUESTED** [review]
Shouldn't we also change it for delete_detail? I guess the query it does can have the same mistake as well, right?

There is a config parameter about if a user can access another users objects. I think it would be better if based on the value of said configuration the user is poped from the kwargs or it stays, so that it gets passed to the query behind or not.

**Comment by hugolarzabal** [comment]
currently, the delete_detail method doesn't check the user at all. Should it do it?

Also, I think there should be a different check and error message if the user is not allowed to access this object instead of leaving user in the kwargs. The current message "The data entity does not exist on the database" is very confusing when you know that the data exist.

**Comment by ggsdc** [comment]
> currently, the delete_detail method doesn't check the user at all. Should it do it?
> 
> Also, I think there should be a different check and error message if the user is not allowed to access this object instead of leaving user in the kwargs. The current message "The data entity does not exist on the database" is very confusing when you know that the data exist.

The user should still be going in the kwargs as the query that is performed need to take it in the case that a use can only access it own objects. If all users can access all objects, then the user is taken out of the kwargs as the query does not needed.

The messages where that way on purpose. In case a user is trying to access information that is not his/hers we do not want to tell them if the information does exists but the user does not have access to it, I prefer to just tell them that it does not exist.

I will make the needed changes on Monday and create the appropriate tests to make sure that this works.

**Comment by hugolarzabal** [comment]
If you do not want users to access data from other users, I think the get_detail method should also be changed.

Also, I would suggest putthing "the data doesn't exist or you do not have permission" in the message if you want to maintain it the same for both cases.

**Comment by ggsdc** [comment]
> If you do not want users to access data from other users, I think the get_detail method should also be changed.
> 
> Also, I would suggest putthing "the data doesn't exist or you do not have permission" in the message if you want to maintain it the same for both cases.

Actually, no changes are needed on the endpoints to adapt it, just creating a get_one_object query on the meta model that all models inherit from is enough.

It is how it is working on the instances or executions models for example. I'm going to test this out and if it works then I will close this PR

**Pull request closed without merging**
